CREATE TABLE EMPLOYEES
(ID INT PRIMARY KEY IDENTITY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
GENDER VARCHAR(20),
SALARY MONEY,
ADDRESS VARCHAR(120)
)
INSERT INTO EMPLOYEES VALUES
('RAKESH','SHARMA','MALE',12000,'NOIDA'),
('MAHESH','SHARMA','MALE',12000,'MP'),
('ANKIT','VERMA','MALE',15000,'NOIDA'),
('RAJESH','VERMA','MALE',12000,'DELHI'),
('MANOJ','KUMAR','MALE',16000,'NOIDA');
